c_compiler:
- gcc
c_compiler_version:
- '12'
cdt_name:
- cos7
cdt_arch:
- armv7l
channel_sources:
- conda-forge,defaults
channel_targets:
- conda-forge main
docker_image:
- quay.io/condaforge/linux-anvil-comp7
libiconv:
- '1.17'
perl:
- 5.32.1
pin_run_as_build:
  libiconv:
    max_pin: x.x
  perl:
    max_pin: x.x.x
target_platform:
- linux-armv7l
